import getCertainConditions from '@utils/certainConditions';
import type { SelectOptions } from '_types';

const getLayoutFile = (configOptions: SelectOptions) => {
  const { hasSwr, hasTanstackQuery } = getCertainConditions(configOptions);

  const reactQueryProvider = `
import ReactQueryProvider from 'providers/reactQueryProvider'
`;
  const swrProvider = `  
import SWRProvider from 'providers/swrProvider'
`;

  const importLibrary = () => {
    if (hasTanstackQuery) {
      return reactQueryProvider;
    }
    if (hasSwr) {
      return swrProvider;
    }
    return '';
  };
  const children = () => {
    if (hasTanstackQuery) {
      return `<ReactQueryProvider>{children}</ReactQueryProvider>`;
    }
    if (hasSwr) {
      return `<SWRProvider>{children}</SWRProvider>`;
    }
    return `{children}`;
  };

  const file = `import { Inter } from 'next/font/google'
import { ReactNode } from 'react'

import './globals.css'
${importLibrary()}
// eslint-disable-next-line new-cap
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        ${children()}
      </body>
    </html>
  )
}
`;

  return file;
};

export default getLayoutFile;
